### ISSUE TITLE
angular-masonry doesn't work with angular 1.2.27

### ISSUE THREAD

**Issue by cladera** [passy/angular-masonry#95]
Hi,

This library is not working with angular 1.2.27 version. 

This is the error I get: 
TypeError: undefined is not a function
    at preLink (http://dev.yobui.com:9000/bower_components/angular-masonry/angular-masonry.js:117:19)
    at nodeLinkFn (http://dev.yobui.com:9000/bower_components/angular-scenario/angular-scenario.js:16509:13)
    at compositeLinkFn (http://dev.yobui.com:9000/bower_components/angular-scenario/angular-scenario.js:15923:13)
    at publicLinkFn (http://dev.yobui.com:9000/bower_components/angular-scenario/angular-scenario.js:15819:30)
    at link (http://dev.yobui.com:9000/bower_components/angular-route/angular-route.js:915:7)
    at nodeLinkFn (http://dev.yobui.com:9000/bower_components/angular-scenario/angular-scenario.js:16529:13)
    at compositeLinkFn (http://dev.yobui.com:9000/bower_components/angular-scenario/angular-scenario.js:15923:13)
    at publicLinkFn (http://dev.yobui.com:9000/bower_components/angular-scenario/angular-scenario.js:15819:30)
    at $get.boundTranscludeFn (http://dev.yobui.com:9000/bower_components/angular-scenario/angular-scenario.js:15943:21)
